FROM python:3.6.5-stretch

WORKDIR /stoacont

ADD . ./

RUN pip install --upgrade pip
RUN pip install cwltool
RUN pip install grpcio-tools

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./action.proto

EXPOSE 7000

ENV NAME Stoa container

CMD ["python","action.py"]
