FROM python:3.6.5-stretch

WORKDIR /stoacont

ADD . ./

RUN pip install --upgrade pip
RUN pip install cwltool
RUN pip install grpcio-tools
RUN pip install astropy

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./action.proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./userstate.proto

RUN apt-get update && apt-get install -y dos2unix

RUN dos2unix actions/*.py
RUN dos2unix actions/*.cwl
RUN dos2unix actions/*.yml

EXPOSE 7000

ENV NAME Stoa Action Server

CMD ["python","action.py"]
